// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.ContextDb;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ZacContext))]
    [Migration("20240802222322_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.DbModels.Alimento", b =>
                {
                    b.Property<int?>("IdAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdAlimento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("IdAlimento");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("Domain.DbModels.CategoriaAlimento", b =>
                {
                    b.Property<int?>("IdCategoriaAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdCategoriaAlimento"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCategoriaAlimento");

                    b.HasIndex("Categoria")
                        .IsUnique();

                    b.ToTable("CategoriaAlimentos");
                });

            modelBuilder.Entity("Domain.DbModels.PacientePadecimiento", b =>
                {
                    b.Property<Guid>("IdPacientePadecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid");

                    b.Property<int>("IdPadecimiento")
                        .HasColumnType("integer");

                    b.HasKey("IdPacientePadecimiento");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdPadecimiento");

                    b.ToTable("PacientePadecimientos");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.Paciente", b =>
                {
                    b.Property<Guid>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdPaciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.PacienteContacto", b =>
                {
                    b.Property<Guid>("IdPacienteContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("GastoSemanal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.HasKey("IdPacienteContacto");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("PacienteContacto");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.PacientePersonales", b =>
                {
                    b.Property<Guid>("IdPacientePersonales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Edad")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdPacientePersonales");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("PacientePersonales");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.PacienteSintomasAntecedentes", b =>
                {
                    b.Property<Guid>("IdPacienteSintomas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AntecedentesFamiliares")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AntecedentesPersonales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdPaciente")
                        .HasColumnType("uuid");

                    b.Property<string>("Signos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPacienteSintomas");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("PacienteSintomasAntecedentes");
                });

            modelBuilder.Entity("Domain.DbModels.Padecimiento", b =>
                {
                    b.Property<int>("IdPadecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPadecimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPadecimiento");

                    b.ToTable("Padecimientos");
                });

            modelBuilder.Entity("Domain.DbModels.Alimento", b =>
                {
                    b.HasOne("Domain.DbModels.CategoriaAlimento", "categoriaAlimentoNav")
                        .WithMany("AlimentosNav")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoriaAlimentoNav");
                });

            modelBuilder.Entity("Domain.DbModels.PacientePadecimiento", b =>
                {
                    b.HasOne("Domain.DbModels.Pacientes.Paciente", "Paciente")
                        .WithMany("PacientePadecimientos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.DbModels.Padecimiento", "Padecimiento")
                        .WithMany("PacientePadecimientos")
                        .HasForeignKey("IdPadecimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Padecimiento");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.PacienteContacto", b =>
                {
                    b.HasOne("Domain.DbModels.Pacientes.Paciente", "Paciente")
                        .WithOne("Contacto")
                        .HasForeignKey("Domain.DbModels.Pacientes.PacienteContacto", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.PacientePersonales", b =>
                {
                    b.HasOne("Domain.DbModels.Pacientes.Paciente", "Paciente")
                        .WithOne("Personales")
                        .HasForeignKey("Domain.DbModels.Pacientes.PacientePersonales", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.PacienteSintomasAntecedentes", b =>
                {
                    b.HasOne("Domain.DbModels.Pacientes.Paciente", "Paciente")
                        .WithOne("SintomasAntecedentes")
                        .HasForeignKey("Domain.DbModels.Pacientes.PacienteSintomasAntecedentes", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.DbModels.CategoriaAlimento", b =>
                {
                    b.Navigation("AlimentosNav");
                });

            modelBuilder.Entity("Domain.DbModels.Pacientes.Paciente", b =>
                {
                    b.Navigation("Contacto")
                        .IsRequired();

                    b.Navigation("PacientePadecimientos");

                    b.Navigation("Personales")
                        .IsRequired();

                    b.Navigation("SintomasAntecedentes")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DbModels.Padecimiento", b =>
                {
                    b.Navigation("PacientePadecimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
