// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.ContextDb;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ZacContext))]
    [Migration("20240728015300_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.DbModels.Alimento", b =>
                {
                    b.Property<int>("IdAlimento")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAlimento");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("Domain.DbModels.CategoriaAlimento", b =>
                {
                    b.Property<int>("IdCategoriaAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoriaAlimento"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCategoriaAlimento");

                    b.HasIndex("Categoria")
                        .IsUnique();

                    b.ToTable("CategoriaAlimentos");
                });

            modelBuilder.Entity("Domain.DbModels.Alimento", b =>
                {
                    b.HasOne("Domain.DbModels.CategoriaAlimento", "categoriaAlimentoNav")
                        .WithMany("AlimentosNav")
                        .HasForeignKey("IdAlimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoriaAlimentoNav");
                });

            modelBuilder.Entity("Domain.DbModels.CategoriaAlimento", b =>
                {
                    b.Navigation("AlimentosNav");
                });
#pragma warning restore 612, 618
        }
    }
}
